---
sudo: false

language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tree

install:
  - composer install
  - composer require php-coveralls/php-coveralls
  - mkdir -p build/logs build/cov

script:
  - vendor/bin/phpunit -c phpunit.xml.dist
  
after_success:
  - cat build/cov/coverage.cov
  - travis_retry php vendor/bin/coveralls
  - tree
...
