---
sudo: false

language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  
git:
  depth: 1

install:
  - composer install
  - mkdir -p build/logs build/cov

script:
  - vendor/bin/phpunit -c phpunit.xml.dist
  
after_success:
  - travis_retry php vendor/bin/coveralls
...
