---
sudo: false

language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install
  - composer require php-coveralls/php-coveralls

script:
  - vendor/bin/phpunit
  
after_script:
  phpunit --coverage-clover build/logs/clover.xml
...
