---
sudo: false

language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

install:
  - composer install
  - composer require php-coveralls/php-coveralls
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit -c phpunit.xml.dist
  
after_success:
  - travis_retry php vendor/bin/coveralls
...
