---
sudo: false

language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - composer require php-coveralls/php-coveralls
  - mkdir -p build/logs

after_success:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
...
